### ISSUE TITLE
Open AbstractFilter

### ISSUE THREAD

**Issue by halfabench** [pixijs/pixi-haxe#10]
Hi,
I am trying to create a custom filter in Haxe. 

1 / However, the current wrapper for the AbstractFilter class forces two args: 

> fragmentSrc:Array<String> 
> and uniforms:Dynamic. 

If you could make these args optional it would allow for customisation. (ie: do some computation before setting them). in Javascript, it already works like this (https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/filters/ColorStepFilter.js for instance)

2 / the current implementation misses several vars : 

> passes : Array<AbstractFilter>
> shaders : Array<Dynamic> ?? (haven't used yet and did not find any code using it..)
> uniforms : Dynamic
> fragmentSrc : Array<String>

( ref https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/filters/AbstractFilter.js )

Thanks!

**Comment by adireddy** [comment]
I haven't used filters much, so it's good that you are using and testing them :)

Will fix 1 now.

Coming to 2, the variables you mentioned are all marked as private in pixi. Are they supposed to be public?

**Comment by adireddy** [comment]
ok got it. will do a quick release in a few mins.

**Comment by adireddy** [comment]
Done.
