### ISSUE TITLE
Full screen problem with IOS on landscape orientation.

### ISSUE THREAD

**Issue by RedYggdrasil** [pixijs/pixi-haxe#101]
Hi,
I have a problem with Haxe and PixiJs while using the “full screen” (bar are still here, just use all the available web space) view on IOS (tested with safari), when I turn my IPhone to portraits, then back in landscape, the view is no longer centered, but “scrolled down”, which is a problem, as it should be full screen, and force the user, if html accept it to scroll up again.
The bug is visible also on your Bunny Mark demo: 
https://github.com/pixijs/pixi-haxe/tree/dev/samples/bunnymark

Thanks,
Red.

![bunnyproblem](https://cloud.githubusercontent.com/assets/15359127/21607413/2c185186-d1b6-11e6-87af-fddc7c58f543.jpg)

**Comment by GaryTsang** [comment]
Dude, I dont think this is a Haxe or Pixi issue. It is how iOS /Safari behaves. There are work around solutions out there for example Brim.

**Comment by RedYggdrasil** [comment]
Hi and thanks for the fast answer,

I have found a Pixi example which doesn’t have the problem http://www.goodboydigital.com/runpixierun/
Don't know how they manage it, I'm looking the source code.
I don’t know what “brim” refer to, could you give me more informations?
Thank you and have a nice day.

**Comment by GaryTsang** [comment]
sure, Brim is here:
https://github.com/gajus/brim

**Comment by alamboley** [comment]
Jumping into this issue too! Brim seems to be pretty old and not relay maintained. Also can't find subject bringing pixijs & brim together, which is weird because everyone should have this issue! Also I can't find anything related to Brim in the Run Pixie Run above...

I'd the same issue with a threejs project, so I think the problem is mostly on HTML/CSS part rather than JS. What do you think @adireddy?

**Comment by GaryTsang** [comment]
The issue, well is not an issue but a behaviour in iOS that is not reported via conventional JS events. And is not related to pixi, Haxe or JS per-say. Happy to be corrected if I'm wrong :)

Agreed, Brim is old and not really maintained now. I haven't used any other alternatives yet so can't comment but would be happy to hear others' thoughts and experience.

**Comment by adireddy** [comment]
Agree. It's iOS specific issue and not related to pixi or haxe.

I haven't used/heard about any other alternative solutions apart from brim.
