### ISSUE TITLE
Detector or PIXI.autoDetectRenderer no longer available? 

### ISSUE THREAD

**Issue by ianharrigan** [pixijs/pixi-haxe#105]
I have some code in a project that was using the `Detector` extern, but it seems to longer be available... Is this an oversight or is there some other way to achieve this?

Cheers,
Ian

**Comment by adireddy** [comment]
There is a new Application class in Pixi v4.3.4 which uses autoDetectRenderer.

`var app = new pixi.core.Application(width, height, renderingOptions);`

**Comment by adireddy** [comment]
I will also add the Detector class back for backward compatibility.

**Comment by ianharrigan** [comment]
Great! Thanks loads! :-)
