### ISSUE TITLE
InteractionData::identifier

### ISSUE THREAD

**Issue by NicolasVereenoghe** [pixijs/pixi-haxe#106]
Hello, thank you so much for these externs.

Can you please, in a next commit, include the InteractionData::identifier property ? Again, thanks for the great work :)

I've been using this property in pixi v3 for multitouch gameplays, it's really nice it has been included in pixi v4.

**Comment by adireddy** [comment]
Sure. Will do :)

**Comment by adireddy** [comment]
added in v4.3.3
