### ISSUE TITLE
Dynamic overload for DisplayObjectContainer::addChild

### ISSUE THREAD

**Issue by aidangrabe** [pixijs/pixi-haxe#11]
A few of the methods in DisplayObjectContainer seem to have overloads for Dynamic types such as [addChild](https://github.com/adireddy/haxe-pixi/blob/master/pixi/display/DisplayObjectContainer.hx#L49).

Is there any reason for this or should they be changed to stricter types?
Looking at the history of the file they seem to only be there for backwards compatibility with older versions of haxe-pixi?

**Comment by adireddy** [comment]
No longer need those overloads. Will update in the next release. Thanks for pointing that @aidangrabe.
