### ISSUE TITLE
BlendMode / BlendModes

### ISSUE THREAD

**Issue by markknol** [pixijs/pixi-haxe#127]
Can you double check the usage of BlendMode / BlendModes? 

I see `Sprite.blendMode` is a `BlendMode` type, but `Graphics.blendMode` is of type `Int`

There seem other cases where the `blendMode` field is `Int` : https://github.com/pixijs/pixi-haxe/search?utf8=%E2%9C%93&q=BlendMode&type=

**Comment by modjke** [comment]
Should be resolved now

**Comment by ivanpopelyshev** [comment]
Btw, about blendModes, there 's https://github.com/pixijs/pixi.js/pull/4049 and I'll propose it for v5.
