### ISSUE TITLE
Haxe externs for PixiParticles

### ISSUE THREAD

**Issue by halfabench** [pixijs/pixi-haxe#13]
Hi, 
I just wrote the externs for PixiParticles (https://github.com/CloudKidStudio/PixiParticles).
They are of course based on haxe-pixi defs so I wanted to know if you would be interested to add them to the haxe-pixi project or would prefer me to push them to a new github repository?

**Comment by adireddy** [comment]
hey @halfabench sure.

Coincidentally I have created a `plugins` package in pixi today and working on pixi input addon (a way to add input fields, buttons, combo box, etc)

I am happy to add particles to the `plugins` package.

I haven't committed anything yet, so can you create `plugins.particles` package with all your externs and raise a pull request.
