### ISSUE TITLE
Particles aren't up to date

### ISSUE THREAD

**Issue by alamboley** [pixijs/pixi-haxe#139]
Hey, is there any schedule for updating [ParticleContainer](https://github.com/pixijs/pixi-haxe/blob/dev/src/pixi/particles/ParticleContainer.hx) to [latest one](https://github.com/pixijs/pixi-particles)?

**Comment by adireddy** [comment]
Are you talking abt pixi-particles contributed by @halfabench https://github.com/pixijs/pixi-haxe/pull/28 ?

**Comment by alamboley** [comment]
No this one https://github.com/pixijs/pixi-haxe/blob/dev/src/pixi/particles/ParticleContainer.hx which can't be used anymore.
Concerning the issue you mentionned, I see things into pixi/plugins/particles/cloudkid/AnimatedParticle.hx but they don't exist anymore? Cloudkit doesn't exist anymore in Pixi.js

**Comment by adireddy** [comment]
Not sure what you mean. What's the issue with https://github.com/pixijs/pixi-haxe/blob/dev/src/pixi/particles/ParticleContainer.hx?

It's used in bunnymark test.
https://github.com/pixijs/pixi-haxe/blob/dev/samples/src/bunnymark/Main.hx

**Comment by alamboley** [comment]
Well indeed it works but it has less options than the new (official) plugin.
The new particle system comes with an editor https://github.com/pixijs/pixi-particles-editor so it would be nice to be able to use those files generated directly.
Do you add plugins to the externs?

**Comment by adireddy** [comment]
pixi-particles is not here atm and of course, it can be added. I don't use particles and I can take a look when I get a chance. If you can contribute, I am fine with that as well.

There is a plugins folder which already has spine and dragon bones externs.
