### ISSUE TITLE
Erroneous specification for InteractionData::identifier ?

### ISSUE THREAD

**Issue by NicolasVereenoghe** [pixijs/pixi-haxe#143]
I noticed this property is specified to be an integer into externs.

But, into the pixi.js v4.5.5 file, and also when I log the interaction datas, when mouse is pressed, the identifier has a String value : "MOUSE"
line 33892 :
`var MOUSE_POINTER_ID = 'MOUSE';`

It's a bit confusing, as this property looks to be also specified as a number into the pixi.js file, line 33591 :
```
/**
 * Unique identifier for this interaction
 *
 * @member {number}
 */
this.identifier = null;
```

So it's an "hybrid" property ? Intended ?

EDIT : I will forward the issue to pixi.js github repository, it's more related to it ...
EDIT2 : https://github.com/pixijs/pixi.js/issues/4373

**Comment by adireddy** [comment]
changed `identifier` to `EitherType<String, Int>`
