### ISSUE TITLE
TextMetrics width/height properties

### ISSUE THREAD

**Issue by dyarosla** [pixijs/pixi-haxe#156]
Should TextMetrics expose width and height values (and more?)? 

http://pixijs.download/dev/docs/PIXI.TextMetrics.html

measureText() returns a TextMetrics object with width/height values, but the TextMetrics class doesn't expose those values.

https://github.com/pixijs/pixi-haxe/commits/dev/src/pixi/core/text/TextMetrics.hx

Should add in var width:Float, var height:Float, etc.

**Comment by notboring** [comment]
See #164
