### ISSUE TITLE
Type not found : pixi.plugins.app.Application

### ISSUE THREAD

**Issue by ghost** [pixijs/pixi-haxe#157]
Hello,

I think I'm missing something. This is my first time using externs with Haxe.

What I did was installing pixijs through haxelib.
Then in flashdevelop / haxedevelop (tried in both) I added the pixijs as a reference.
Inside the editor it says 
> src/Main.hx:4: characters 7-35 : Type not found : pixi.plugins.app.Application

Here is a screenshot of my IDE
[screenshot](https://i.imgur.com/7vMaela.png)

What I'm doing wrong?

**Comment by SlavaRa** [comment]
Can you update Project Template and update files in `your_project/bin/libs`?

Project template: https://github.com/SlavaRa/fdproject-haxe-pixijs
Libraries: https://github.com/pixijs/pixi-haxe/tree/dev/libs

**Comment by SlavaRa** [comment]
Can you disable `Tools -> Plugins -> LintingHelper`?
(Inside the editor it says -> compiler says)

**Comment by ghost** [comment]
Done!
It was something really simple. I was referencing the pixi folder instead of the src folder
