### ISSUE TITLE
Runtime errors for compiled examples

### ISSUE THREAD

**Issue by Ujimych** [pixijs/pixi-haxe#170]
Library examples are compiled without errors.
Errors appear at [runtime](https://prnt.sc/sykqcc).

A compiled example of "basics" is available [here](https://gist.github.com/Ujimych/6d7967f1e3fa60fc29a55721fdfbed67).

I also want to note that the "libs" folder contains old versions of the library, which creates inconvenience.

I used the latest pixijs from haxelib and haxe 4.1.1

**Comment by notboring** [comment]
The examples and the lib folder are outdated. Here's what you need to change:

https://github.com/pixijs/pixi-haxe/pull/171/commits/28041113d0d8f37dd477f38465ab9e80c1ec33e3

The result using haxe 4.0.5/pixi 5:

https://notboring.github.io/demos/haxe-pixi/basics.html
