### ISSUE TITLE
DisplacementFilter: new is missing texture arg

### ISSUE THREAD

**Issue by halfabench** [pixijs/pixi-haxe#4]
Hi, the DisplacementFilter new requires a texture argument to work properly.
doc : http://www.goodboydigital.com/pixijs/docs/classes/DisplacementFilter.html.

Anyway, thanks for the awesome work. Using pixi.js from haxe is so refreshing :)

**Comment by adireddy** [comment]
Thanks @halfabench :)

Haven't tested the filters at all. Just noticed a few other issues as well like every filter class should be extending AbstractFilter, etc.

**Comment by adireddy** [comment]
Will release an update very soon.

**Comment by adireddy** [comment]
Fixed and just released v2.1.2 to haxelib.
