### ISSUE TITLE
particle 

### ISSUE THREAD

**Issue by halfabench** [pixijs/pixi-haxe#49]
Hi!
Great work you did on the v3. I'm currently moving my pixiV2 haxe projects to v3. Thanks for the hard work!

No just to know: should I move the the haxe wrappers for pixi-particles outside of pixi-haxe? Or do you intend to move them back here?
Thanks!

**Comment by adireddy** [comment]
No problem :)

You can leave them there in 2.x branch.

**Comment by halfabench** [comment]
ok :)
