### ISSUE TITLE
DisplayObject.hitArea fallback to Dynamic

### ISSUE THREAD

**Issue by halfabench** [pixijs/pixi-haxe#5]
Hi!
I am using a circle instead of a rectangle for my hitArea. It does not work since you are waiting for a Rectangle. 
You used to use a Dynamic instead in v1.6 and it was working. Can you revert to Dynamic? Thanks!

Reference: http://www.goodboydigital.com/pixijs/docs/classes/DisplayObject.html#property_hitArea

**Comment by adireddy** [comment]
fixed in master
