### ISSUE TITLE
new BaseTexture(source:String, ..) should be Element

### ISSUE THREAD

**Issue by bartvanheukelom** [pixijs/pixi-haxe#51]
The mapping of the `BaseTexture` constructor is wrong. `source` is declared a `String` but it should be `js.html.Element` so it can take an Image or a Canvas. Or define 2 overloads, if that's possible.

     /**
      * @param source {Image|Canvas} the source object of the texture.
      */
     function new(source:String, ?scaleMode:Int, ?resolution:Float);

**Comment by adireddy** [comment]
Fixed in v3.0.8
