### ISSUE TITLE
Video demo does not work in iOS Safari 

### ISSUE THREAD

**Issue by DimuDesigns** [pixijs/pixi-haxe#53]
Tested the video demo link on an iPhone 5S running version 8.3 and there was no playback just a black box where the video should be and a FPS counter.

**Comment by adireddy** [comment]
Video has lot of issues on various os/device combinations.

I have raised an issue with pixi a while ago https://github.com/GoodBoyDigital/pixi.js/issues/1485 and you can more info there based on your testing.

I ended up using HTML 5 video element behind pixi renderer and made pixi renderer transparent. Everything still controlled in Haxe though.
