### ISSUE TITLE
Application.hx null getter

### ISSUE THREAD

**Issue by alamboley** [pixijs/pixi-haxe#55]
Hey, thanks for those awesome externs!

In the Application.hx why does the pixelRatio, skipFrame, width, height, transparent, antialias, forceFXAAA, autoResize, backgroundColor have their getter set to null?

**Comment by adireddy** [comment]
Hey @alamboley Thanks.

No specific reason, all my use cases only need to set them so thought making them write only make sense.

But if you want read access to those I can change them.

**Comment by alamboley** [comment]
Hey, yeah I would like to be able to read my game width in real time, without having to add a new var at the same time than setting its size.

I saw your latest commit. Thanks !

**Comment by adireddy** [comment]
np, will release it to haxelib tomorrow.

**Comment by alamboley** [comment]
:+1:

**Comment by adireddy** [comment]
just released [v3.0.11](http://lib.haxe.org/p/pixijs)

**Comment by alamboley** [comment]
Well unfortunately, it sounds that your latest changes haven't been pushed to this new version http://lib.haxe.org/p/pixijs/3.0.11/files/pixi/plugins/app/Application.hx :/

**Comment by adireddy** [comment]
don't know what happened there, could be sync issues.
released v3.0.12
http://lib.haxe.org/p/pixijs/3.0.12/files/pixi/plugins/app/Application.hx

**Comment by alamboley** [comment]
:+1:
