### ISSUE TITLE
Overriding width / height

### ISSUE THREAD

**Issue by ianharrigan** [pixijs/pixi-haxe#63]
Hi, im wondering how it would be possible to override the width and height in parent classes to implement custom logic, eg:

```haxe
class Something extends Graphics {
    public override set_width(value:Float):Float {
        // something custom
        return value;
    }
}
```

The problem seems to be that width and height are just vars, rather than getters / setters. Ive managed to get around this by commenting out width in the extern and adding:

``` haxe
	public var width(get, set):Float;
	@:getter(width)
	public function get_width():Float {
            ...
	}
	
	@:setter(width)
	public function set_height(value:Float):Float {
            ...
	    return value;
	}
```

But obviously this isnt correct as it means i have to edit the externs and also means i have to add the vars to "Text.hx", do you have any advice of how to do this, or are there any plans to make the externs use getters/setters so they can be overriden?

Cheers,
Ian

**Comment by adireddy** [comment]
Hi @ianharrigan, I see your point but I don't think it's possible to add getters and setters at extern level.

May be I am wrong as I haven't tried that before. If you have time can you please give it a go probably in the `Container` class in externs and let me know if it works.

**Comment by ianharrigan** [comment]
Cool, thanks for the answer, ill try it when i get a moment, at the moment, ive actually found another way to do it... Ive basically created my own extern:

```haxe
@:native("PIXI.Container")
extern class HaxeUIPixiContainer extends DisplayObject {
}
´´´
Which is basically a copy of yours without the width / height and then i set them in my parent class, it means i dont have to touch your externs and can still have control over my version of it... So far they all seem to play nicely together. 

Still, ill see ifi can find out more about using actual setters, i had a quick play, and apart from `var width(default, default):Float` (which is no good really) i could figure it out.

**Comment by adireddy** [comment]
Closing this for now...

**Comment by ianharrigan** [comment]
Yeah, sorry, totally forgot...
