### ISSUE TITLE
OpenFL/Haxeflixel integration?

### ISSUE THREAD

**Issue by ThunderXBlitZ** [pixijs/pixi-haxe#65]
Hi, Im new to haxe, is it possible to use this together with openFL/haxeflixel. I come from a Flash background and this would be brilliant for cross-platform games

**Comment by adireddy** [comment]
Hi @ThunderXBlitZ, No it's not possible.

I created these externs only for Html5/JS target. OpenFL/Haxeflixel has it's own html5 backend so if are looking to build cross-platform games then I definitely recommend using OpenFL/Haxeflixel.

BTW, I am from flash background :)

**Comment by hopewise** [comment]
Anyone can apply pixi filter on openFL's sprite or bitmap? is it easy?
