### ISSUE TITLE
Retina example doesn't seem to work

### ISSUE THREAD

**Issue by SlawomirMazgaj** [pixijs/pixi-haxe#66]
Hello,
I was recently doing some tests with scaling etc and it feels like renderingOptions.resolution doesn't make any difference. At first I was trying to use twice as big image for same resolution but double pixelRatio. First results didn't makes any sense so I moved from device to chrome Dev tools. It wasn't any better after that so I went back to github example.

Here what I'm expecting:
img@1x.jpg     is 960x600
img@2x.jpg     is 1920x1200
so img 2 is 2 times bigger than img1

If I run it on 960x600 screen with pixelRatio = 1 I should be able to see whole image, just like that, right?
![times1](https://cloud.githubusercontent.com/assets/2122619/10204370/3fb039de-67b3-11e5-8e0c-328a000fc3f5.png)

So.... Running on same resolution but with pixelRatio = 2 should load bigger image (twice as big) and I still should see exactly same thing, right? If the answer is YES, then I have some bad news:
![times2](https://cloud.githubusercontent.com/assets/2122619/10204534/3e1d7158-67b4-11e5-94e1-a6949eb28a70.png)

So now my question is:
-Is there something wrong with my understanding of this or something is actually not working properly?

Best Regards,
Slawomir

**Comment by adireddy** [comment]
Hi @SlawomirMazgaj, I have changed the retina prefix for some other testing in the code and forgot to change it back.

Anyway I fixed it and the same is working fine. http://adireddy.github.io/demos/pixi-haxe/retina.html
