### ISSUE TITLE
Performance drop for haxe version?

### ISSUE THREAD

**Issue by trsh** [pixijs/pixi-haxe#72]
Why does http://www.goodboydigital.com/pixijs/bunnymark_v3/  outperform haxe bunnies http://adireddy.github.io/demos/pixi-haxe/bunnymark.html ? I have a weak computer, so I can see that very clearly. Same window size - the haxe port bunny mark goes below 45 fps on 1500 bunnies. Js version on 6000.

**Comment by adireddy** [comment]
The code is not exactly the same for comparison but I can assure you haxe has nothing to do with it :)

pixi source - http://www.goodboydigital.com/pixijs/bunnymark_v3/js/bunnyBenchMark.js
pixi-haxe source - https://github.com/pixijs/pixi-haxe/blob/dev/samples/bunnymark/Main.hx

A few differences between the samples:
- stage size 800x600 (pixi) vs dynamic window.innerWidth x window.innerHeight (haxe)
- single texture http://www.goodboydigital.com/pixijs/bunnymark_v3/bunnys.png (pixi) vs multiple images in haxe (http://adireddy.github.io/demos/pixi-haxe/assets/bunnymark/bunny1.png, 2, 3, 4, 5)
- pixi.js version v3.0.0 (pixi) vs v3.0.8 (haxe)

**Comment by trsh** [comment]
"pixi.js version v3.0.0 (pixi) vs v3.0.8 (haxe)"

this point should not be an issue, but an advance :)

**Comment by adireddy** [comment]
true :)

Updated demo to use pixi 3.0.9 and also using single texture now. Let me know if it made any difference.

**Comment by trsh** [comment]
I did some tests on mobile. 6200 bunnies:
Haxe-pixi: 38 FPS
pixi.js: 45 FPS

Same screen size, and now same texture
