### ISSUE TITLE
Version number downgraded

### ISSUE THREAD

**Issue by Rollo-Liu** [pixijs/pixi-haxe#79]
By some reason Haxelib think the latest version of this lib is "2.3.2" http://lib.haxe.org/p/pixijs.

It should be "3.0.31" based on the `haxelib.json`.

**Comment by adireddy** [comment]
I merged a pull request for pixi v2 externs recently so haxelib thinks it's the latest version.

3.0.31 is at http://lib.haxe.org/p/pixijs/3.0.31/

**Comment by Rollo-Liu** [comment]
Oh I see. Thanks! Didn't know still maintaining v2 supports.
