### ISSUE TITLE
[minor]cannot access new PIXI.Graphics().graphicsData

### ISSUE THREAD

**Issue by thesunlover** [pixijs/pixi-haxe#83]
the graphicsData array is not listed in the core.display.graphics.Graphics.hx

**Comment by adireddy** [comment]
@thesunlover it was marked as private and that's the reason why it's not there.
https://github.com/pixijs/pixi.js/blob/dev/src/core/graphics/Graphics.js#L50

Added it and released v3.1.2 to haxelib.
