### ISSUE TITLE
Can't access PIXI.utils.TextureCache from Haxe

### ISSUE THREAD

**Issue by alamboley** [pixijs/pixi-haxe#84]
Hey, I didn't find a way to use it via Haxe. At the moment I'm using an untyped to access it:

untyped __js__('for (var name in PIXI.utils.TextureCache)
	if (name.indexOf("explosion_") == 0)
		out[out.length] = name;');

**Comment by adireddy** [comment]
Try `pixi.core.utils.Utils.TextureCache`. Should work.

**Comment by alamboley** [comment]
Ok, thanks! Do you success to iterate on this array? I got an error: `You can't iterate on a Dynamic value, please specify Iterator or Iterable`. I try to cast it but without luck so far.

**Comment by alamboley** [comment]
Finally, I did `for (name in Reflect.fields(pixi.core.utils.Utils.TextureCache))` not sure if it's the best way though.

**Comment by adireddy** [comment]
It's not any Array. It's an object https://github.com/pixijs/pixi.js/blob/master/src/core/utils/index.js#L268

So using Reflect should be fine on dynamic objects.

**Comment by alamboley** [comment]
Yeah indeed 👍
