### ISSUE TITLE
How to access drawCount info?

### ISSUE THREAD

**Issue by alamboley** [pixijs/pixi-haxe#85]
Hey, I can't success to trace the drawCount info from https://github.com/pixijs/pixi-haxe/blob/dev/src/pixi/core/renderers/webgl/WebGLRenderer.hx#L38
Is it the number of draw call ?

How do you access it from the app/Application.hx class ?

**Comment by adireddy** [comment]
Should be accessible via renderer instance https://github.com/pixijs/pixi-haxe/blob/dev/src/pixi/plugins/app/Application.hx#L123

**Comment by alamboley** [comment]
Yeah that's what I thought, but `trace(renderer.drawCount);` into an update loop always ouput `undefined` on my side.

**Comment by adireddy** [comment]
I am sure it works. Remember the property is only available in WebGL Renderer. It will be `undefined` in canvas.

**Comment by alamboley** [comment]
Well, I've this output `Pixi.js 4.0.0 - WebGL - http://www.pixijs.com/`, so normally I'm in WebGL mode right?

**Comment by adireddy** [comment]
yes it's webgl mode. I checked in v3 and it works. Could be an issue with v4.

**Comment by alamboley** [comment]
Yeah, seems to be https://github.com/pixijs/pixi.js/issues/2568

**Comment by adireddy** [comment]
this was marked for v5, so closing it
