### ISSUE TITLE
different methods Loader.once in Haxe and JS

### ISSUE THREAD

**Issue by GrafMine** [pixijs/pixi-haxe#87]
Hi, method Loader.once('complete', load);
callback for the 'complete' event of the Loader class - load
in js callback load - may have 2 parameters
in haxe callback load - must have only 1 parameter (and this bug , becouse second parametr have all loaded resourse)

**Comment by adireddy** [comment]
@GrafMine which version of externs are you using? v3 or v4?

**Comment by adireddy** [comment]
Fixed in v3.1.3
