### ISSUE TITLE
What's the convention for js functions outside classes

### ISSUE THREAD

**Issue by Tiago-Ling** [pixijs/pixi-haxe#92]
Where can js files with functions like `pixi.core.graphics.utils.bezierCurveTo` be included? 

I noticed there's `pixi.core.utils.Utils`, is it ok to include them there?

**Comment by adireddy** [comment]
It's not exposed in pixi https://github.com/pixijs/pixi.js/blob/ace34bfeec0a5035c50555f3fb1c84a78eb8d246/src/core/graphics/utils/bezierCurveTo.js#L5

Why do you want to include it?

**Comment by Tiago-Ling** [comment]
I was thinking more of other utilities, but i really didn't noticed that many (all?) of them are not exposed. :)

**Comment by adireddy** [comment]
If you find anything let me know.
