### ISSUE TITLE
ignored params in Text.style

### ISSUE THREAD

**Issue by GrafMine** [pixijs/pixi-haxe#95]
var style = {
      	fontSize:52,// ignored
	fontSize:"52",//ignored
	fontSize:"52px",//ignored
	};
var text = new Text("some");
text.style = style;

**Comment by adireddy** [comment]
Not sure I understand what you mean but I created a sample which works fine.

https://adireddy.github.io/demos/pixi-haxe/text.html

Here is the source for the sample
https://github.com/pixijs/pixi-haxe/blob/dev/samples/text/Main.hx

**Comment by GrafMine** [comment]
Yes, sorry, i update to 4.0.1 and fix it, this sample i write when i had 4.0.0

**Comment by adireddy** [comment]
np 👍
