### ISSUE TITLE
RETINA_PREFIX should be moved to PIXI.settings

### ISSUE THREAD

**Issue by DanScott90** [pixijs/pixi-haxe#98]
Hi, got an issue where our game sets RETINA_PREFIX, this no longer exists in v4.2.1 of pixijs, a bunch of vars have been moved from PIXI to PIXI.settings

Though a comment on v4.2.3 release "Fixes PIXI.settings not being respected" seems to suggest this might have been broken anyway on v4.2.1 and/or v4.2.2.

v4.2.1 changes:
"Moved a bunch of constants to PIXI.settings:
PIXI.settings.RESOLUTION (moved from PIXI.RESOLUTION)
PIXI.settings.FILTER_RESOLUTION (moved from PIXI.RESOLUTION)
PIXI.settings.TARGET_FPMS (moved from PIXI.TARGET_FPMS)
PIXI.settings.MIPMAP_TEXTURES (moved from PIXI.MIPMAP_TEXTURES)
PIXI.settings.SPRITE_BATCH_SIZE (moved from PIXI.SPRITE_BATCH_SIZE)
PIXI.settings.SPRITE_MAX_TEXTURES (moved from PIXI.SPRITE_MAX_TEXTURES)
PIXI.settings.RENDER_OPTIONS (moved from PIXI.DEFAULT_RENDER_OPTIONS)
PIXI.settings.GC_MODE (moved from PIXI.GC_MODES.DEFAULT)
PIXI.settings.TRANSFORM_MODE (moved from PIXI.TRANSFORM_MODE.DEFAULT)
PIXI.settings.SCALE_MODE (moved from PIXI.SCALE_MODES.DEFAULT)
PIXI.settings.RETINA_PREFIX (moved from PIXI.RETINA_PREFIX)
PIXI.settings.WRAP_MODE (moved from PIXI.WRAP_MODES.DEFAULT)
PIXI.settings.PRECISION (moved from PIXI.PRECISION.DEFAULT)"

**Comment by DanScott90** [comment]
@adireddy not sure if you get notified if I post an issue, but guessing you are notified now :)

Need any more information?

**Comment by adireddy** [comment]
Totally missed this one @DanScott90. Will take a look.

**Comment by adireddy** [comment]
I have noticed that `PIXI.RETINA_PREFIX` is still available in 4.2.2

In fact both are available `PIXI.settings.RETINA_PREFIX`

**Comment by adireddy** [comment]
Added a new static `Settings` class in `core` package. Let me know if all is good and I will release it.

**Comment by DanScott90** [comment]
@adireddy Ok thanks, will check, when I was testing with v4.2.2 library I was getting a runtime error when trying to set the PIXI.RETINA_PREFIX

**Comment by adireddy** [comment]
Released v4.2.2 externs so you can test from haxelib directly.

**Comment by DanScott90** [comment]
@adireddy , just got around to testing it out, I think Pixi.hx needs a settings var

**Comment by adireddy** [comment]
of course, it does.. my bad.

Done in v4.2.3
