### ISSUE TITLE
Place original pixi.js in pixi-haxe lib

### ISSUE THREAD

**Issue by andrew-git** [pixijs/pixi-haxe#99]
@adireddy Thanks for you work and supporting pixi-haxe!
Could you add pixi.js file to haxe library for easy work and version control?

Thanks in advance

**Comment by adireddy** [comment]
Hey @andrew-git, can do that but the same version of externs can work with multiple pixi.js versions so it's not ideal to include a specific version.

I recommend using a CDN if that works out for you.
